/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List artifacts, newest identifiers last.
         * @description List artifacts in creation order. Use `next_cursor` from the response to fetch the following page.
         */
        get: operations["list_artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One artifact in detail.
         * @description Fetch one artifact with its components and any structural findings.
         */
        get: operations["get_artifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The artifact's components.
         * @description List the files making up an artifact.
         */
        get: operations["list_components"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The artifact's full manifest, exactly as stored.
         * @description Fetch the artifact manifest exactly as stored, byte for byte.
         */
        get: operations["get_manifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/burn-attempts/{attempt_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit worker events.
         * @description Submit worker events. Idempotent by sequence: resubmitting a batch already held changes nothing.
         */
        post: operations["submit_events"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/burn-attempts/{attempt_id}/lease/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extend a lease.
         * @description Extend a lease. A refusal does not interrupt a write already in progress; it only prevents claiming more work.
         */
        post: operations["renew"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worker-enrollments/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a one-use enrollment token for a worker credential.
         * @description Exchange a one-use enrollment token for a worker credential. The credential is returned once and cannot be recovered.
         */
        post: operations["consume_enrollment_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/{worker_id}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for work.
         * @description Ask for a burn job. Answers 204 when there is nothing to do.
         */
        post: operations["claim_work"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/{worker_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report that a worker is alive.
         * @description Report that a worker is alive and receive any instruction to stop taking new work.
         */
        post: operations["heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe: the process is running and the runtime is responsive.
         * @description Liveness. Answers whenever the process can serve a request and deliberately checks no dependency, so a database outage cannot cause a restart loop.
         */
        get: operations["livez"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe: every dependency needed to serve traffic is usable.
         * @description Readiness. Answers 503 when any dependency is unusable so that traffic is withheld rather than sent into failure.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Everything known about one artifact, short of its full manifest. */
        ArtifactDetail: components["schemas"]["ArtifactSummary"] & {
            /** @description The files making up the artifact. */
            components: components["schemas"]["ComponentView"][];
            /**
             * Format: float
             * @description Detection confidence, from 0 to 1. Diagnostic only.
             */
            format_confidence: number;
            /** @description Where the bytes came from. */
            source_kind: string;
            /** @description Structural findings, if any. */
            warnings: string[];
        };
        /**
         * @description An artifact as it appears in a listing.
         *
         *     Deliberately not the whole manifest: a listing of a large library should
         *     not carry every component of every artifact.
         */
        ArtifactSummary: {
            /** @description Shape of the artifact. */
            artifact_kind: string;
            /** @description Number of files. */
            component_count: number;
            /** @description Detected container format. */
            format: string;
            /**
             * @description Whether anything structural is worth an operator's attention.
             *
             *     Surfaced in the summary so a damaged artifact is visible in a list
             *     without opening it.
             */
            has_warnings: boolean;
            /** @description Opaque identifier. */
            id: string;
            /** @description Filename as received, when one was recorded. */
            source_filename?: string | null;
            /**
             * Format: int64
             * @description Total size of all components.
             */
            total_bytes: number;
            /** @description Structural validation outcome. */
            validation_state: string;
        };
        /**
         * @description A page of artifact summaries.
         *
         *     A concrete type rather than a generic instantiation so the published
         *     OpenAPI names something a client generator can produce cleanly.
         */
        ArtifactSummaryPage: {
            /** @description The artifacts in this page. */
            items: components["schemas"]["ArtifactSummary"][];
            /** @description Cursor for the next page, or null when this is the last. */
            next_cursor?: string | null;
        };
        /** @description What a worker offers when asking for work. */
        ClaimRequest: {
            /** @description The drive the work would run on. */
            drive_id: string;
            /** @description The engine the worker would use. */
            engine: string;
            /** @description That engine's version. */
            engine_version: string;
        };
        /** @description A lease on some work. */
        ClaimResponse: {
            /** @description The artifact to write. */
            artifact_id: string;
            /** @description The attempt created for this claim. */
            attempt_id: string;
            /**
             * Format: int32
             * @description Which attempt this is.
             */
            attempt_number: number;
            /** @description The job. */
            burn_job_id: string;
            /** @description When the lease lapses. */
            lease_expires_at: string;
            /** @description The lease token, presented on subsequent requests for this attempt. */
            lease_token: string;
            /** @description Verification steps the job requires. */
            verification_policy: string[];
        };
        /** @description One file within an artifact. */
        ComponentView: {
            /**
             * Format: int64
             * @description Size in bytes.
             */
            length_bytes: number;
            /** @description Portable path inside the artifact. */
            logical_path: string;
            /**
             * Format: int32
             * @description Position within the artifact.
             */
            ordinal: number;
            /** @description What part it plays. */
            role: string;
            /** @description Content digest, as lowercase hex. */
            sha256: string;
        };
        /** @description The state of one dependency. */
        DependencyCheck: {
            /**
             * @description Operator-facing failure summary. Never carries a connection string or
             *     credential, only the error class.
             */
            detail?: string | null;
            /** @description Dependency name, e.g. `"database"`. */
            name: string;
            /** @description `"up"` or `"down"`. */
            status: string;
        };
        /** @description What a worker sends to enroll. */
        EnrollmentRequest: {
            /** @description The one-use token an administrator issued. */
            enrollment_token: string;
            /** @description A human-meaningful name for this worker. */
            name: string;
            /** @description Protocol versions the worker speaks. */
            protocol_versions: string[];
            /** @description The worker's software version. */
            software_version: string;
        };
        /** @description What a newly enrolled worker receives. */
        EnrollmentResponse: {
            /** @description The credential, returned exactly once and never recoverable. */
            credential: string;
            /**
             * Format: int64
             * @description How often to report in.
             */
            heartbeat_interval_seconds: number;
            /**
             * Format: int64
             * @description How long a lease lasts.
             */
            lease_duration_seconds: number;
            /** @description The protocol version the server selected. */
            protocol_version: string;
            /** @description Its identity. */
            worker_id: string;
        };
        /** @description What the server has persisted. */
        EventAck: {
            /**
             * Format: int64
             * @description The highest contiguous sequence held. The worker prunes against this.
             */
            accepted_through_sequence: number;
        };
        /** @description A batch of events. */
        EventBatch: {
            /** @description The events, in sequence order. */
            events: components["schemas"]["EventSubmission"][];
        };
        /** @description One event in a submitted batch. */
        EventSubmission: {
            /** @description Stable machine-readable code. */
            code: string;
            /** @description Structured detail. */
            data?: unknown;
            /** @description Event type. */
            event_type: string;
            /**
             * Format: float
             * @description Progress from 0 to 1, when reported.
             */
            progress?: number | null;
            /**
             * Format: int64
             * @description Monotonic within the attempt.
             */
            sequence: number;
            /** @description Stage it relates to. */
            stage: string;
            /** @description When the worker observed it. */
            worker_time: string;
        };
        /** @description What the server tells a worker on each heartbeat. */
        HeartbeatResponse: {
            /** @description Whether the worker should stop taking new work. */
            drain: boolean;
            /** @description The server's clock, so a worker can notice drift. */
            server_time: string;
        };
        /** @description Result of a liveness probe. */
        Liveness: {
            /** @description Always `"alive"` when the process can serve a request at all. */
            status: string;
            /** @description Server version, from the crate version at build time. */
            version: string;
        };
        /** @description An RFC 9457 problem document. */
        Problem: {
            /** @description Stable machine-readable code. Clients branch on this, not on `detail`. */
            code: string;
            /** @description Human-readable explanation. May be reworded between releases. */
            detail: string;
            /** @description The request path, when known. */
            instance?: string | null;
            /**
             * Format: int32
             * @description HTTP status code, repeated in the body as the RFC allows.
             */
            status: number;
            /** @description Short human-readable summary. */
            title: string;
            /** @description A URI identifying the problem type. */
            type: string;
        };
        /** @description Result of a readiness probe. */
        Readiness: {
            /** @description Per-dependency detail, so an operator can see *what* is failing. */
            checks: components["schemas"]["DependencyCheck"][];
            /** @description `"ready"` when every dependency is usable, otherwise `"degraded"`. */
            status: string;
        };
        /** @description What a worker sends to renew. */
        RenewRequest: {
            /** @description The lease token from the claim. */
            lease_token: string;
        };
        /** @description The renewed lease. */
        RenewResponse: {
            /** @description The new expiry. */
            lease_expires_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_artifacts: {
        parameters: {
            query?: {
                /** @description Maximum items to return. Clamped to [`MAX_LIMIT`]. */
                limit?: number | null;
                /** @description Opaque cursor from a previous response's `next_cursor`. */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of artifacts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactSummaryPage"];
                };
            };
            /** @description Invalid cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Library unreadable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_artifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Artifact identifier */
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The artifact */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDetail"];
                };
            };
            /** @description No such artifact */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Stored manifest is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_components: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Artifact identifier */
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The components */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentView"][];
                };
            };
            /** @description No such artifact */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_manifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Artifact identifier */
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The manifest document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such artifact */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    submit_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Attempt identifier */
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventBatch"];
            };
        };
        responses: {
            /** @description Accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAck"];
                };
            };
            /** @description Malformed batch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    renew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Attempt identifier */
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenewRequest"];
            };
        };
        responses: {
            /** @description Renewed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenewResponse"];
                };
            };
            /** @description No renewable attempt */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    consume_enrollment_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentRequest"];
            };
        };
        responses: {
            /** @description Enrolled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResponse"];
                };
            };
            /** @description No shared protocol version */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description The token is not usable */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description The name is already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    claim_work: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Worker identifier */
                worker_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimRequest"];
            };
        };
        responses: {
            /** @description Work leased */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimResponse"];
                };
            };
            /** @description Nothing to do */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not this worker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description The drive is already busy */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    heartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Worker identifier */
                worker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acknowledged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not this worker */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    livez: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies usable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description At least one dependency is down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
}
